- src/main.rs
- static/prelude.rs
- supported.cddl
**Codegen cleanup:**
Generated code should be more readable now, as we try harder to generate useful field names.
We also no longer store field such as
```rust
pub struct Foo {
group: groups::Foo,
}
```
to now be
```rust
pub struct Foo(groups::Foo);
```
and likewise for the binary data wrappers.
In the future we could remove the `groups` module and have everything as a part of the root structs. They were an abstraction that was thought would help earlier on, especially if plain groups were represented as both array/map. But now the code generation process is changed and the generation of the exposed wrapper + the inner group data is more coupled rather than being a separate process, so it makes less sense. This would make no difference for the wasm API, but for expanding upon the …
> Generated code cleanup + Optional field setters

- src/main.rs
- static/prelude.rs
Now all field are represented directly inside of the main code,
so instead of both `lib.rs` having
```rust
struct Foo(groups::Foo);
```
and `groups.rs` having
```rust
struct Foo {
x: u32,
y: u32,
}
```
we now have only `lib.rs` having the group structure, but also having the
wasm exposure and other exposed functionality that the `lib.rs` had
before.
This simplifies in-library client code (wasm interface is unchanged)
as instead of `self.0.x.0.y.0` we can just write `self.x.y` and be much
more readable.
This existed before as plain groups and their usage used to be
code-generated in separate steps, as well as a desire to be generic for
both array vs map representations. This does not matter anymore though
as the two (group vs concrete representation) had already became coupled
(and …
> Remove concept of the groups module, simplifying generated code.

- README.md
- src/main.rs
- static/prelude.rs
Only group choice support existed before, but not type choice, ie `foo = x  / y / z` or `foo = { bar: a / b, baz: c / d }`
Now type choices should work as well with some caveats:
* ~primitives in type choices cause issues with rust syntax~
* ~repeated types within a choice (ie with differences in occurrences/size
limits/ets) cause issues (problem with `relays` used in new proposed shelley.cddl as IPV4/IPV6 are just binary bytes but with different sizes~
* ~Isues with byte strings inside type choices~
* ~Not directly related, but we don't support CDDL's null which is used
in the motivating use-cases in shelley.cddl's proposed changes~
* ~Serialization is broke for non-rust-struct types~
* Inlined groups/arrays in type choices don't work in general case - homogeneous array/table types are …
> Type choice support

- src/main.rs
Map structs read the ending Special::Break to know that they are ending,
but we were not checking what kind of Special we encountered since we
don't support Special keys in maps (only true/false make sense anyway)
but that meant that we didn't consume the Special CBOR tag, which caused
problems if a map-represented struct was embedded within another CDDL
structure, as the next structure would read the Special::Break instead
of its own actual first value.
Now we consume the Special value we encounter and throw an error if it
is not Special::Break.
> Fix deserialization for map-represented structs

- src/main.rs
Before this most of the generated code would generate indefinite CBOR lengths due to ease of implementation regarding plain groups embedded in other groups.
This had the a couple drawbacks, namely:
1) Shelley Haskell node immediate compatibility.
The node doesn't support indefinite length deserialization everywhere for CBOR structures yet, so to avoid possible problems in the meantime, we are switching to definite length encodings.
2) Size. This change should result in a slight (~5% for txs approx) size savings as indefinite is 2
bytes always but definite is 1 byte for <24 and 2 bytes for I think <256
lengths.
As the serialization impl had to be refactored to do this, I also
decided to only generated the SerializeEmbeddedGroup impl when necessary
(plain groups only) and just directly …
> Switch to definite length encoding

- example/serialization_unit_tests.rs
- src/main.rs
Now all wasm-exposed functions take by-reference rust-structs and clone
them so that they can't be moved in rust memory which is not obvious
from the js/wasm side. Now everything should be ref+clone()
The BINARY_WRAPPER flag was also added to toggle the behavior of
generating binary wrappers for bytes/bstr aliases.
RustType also now has an Alias variant for when it was the produce of a
user-specified type alias. For reserved keywords this is not used.
> Change wasm-exposed interface to be friendlier

- src/main.rs
- static/prelude.rs
All non-fixed values generate a getter
All enums (group choices + type choices) now generate a FooKind in
addition to the FooEnum which  is wasm-exposed and contains no data, just
specifies which FooEnum the Foo struct is.
These enums also, for data-containing variants, generate an as_* variant
conversion function which returns a copy of the variant if it is that
variant, or else None (undefined from js/wasm) if it's another variant.
> Add getter generation

- example/serialization_unit_tests.rs
- src/main.rs
- static/prelude.rs
Length checks are now done for definite length decoding.
`DeserializeEmbeddedGroup` is now only generated when necessary (plain
groups), and otherwise everything is directly inlined into `Deserialize`
to minimize code and not generate unncessary interfaces.
Various clean-ups were done as well on the code.
Everything has been tested against the code in
`example/serialization_unit_tests.rs` in both definite and indefinite
deserialization.
One test there was changed to go from `Map<String, String>` to `Map<Uint,
String>` due to a bug introduced in a previous change adding in key
set getting functionality to maps.
> Add deserialize length checks + shorten generated code

- src/cmd.rs
- src/generation.rs
- src/intermediate.rs
- static/Cargo.toml
CBOR has several ways to vary in the bytes encoded from a single
semantically-equal piece of information:
1) Map ordering of keys
2) Integer encodings (1 vs 4 bytes) (includes length for major types)
3) Definite vs indefinite lengths of arrays/maps (and strings)
We implement 1 and 3 (excluding for strings) here as 2 would require
changes to `cbor_event` and for our purposes (Cardano blockchain) we've
never seen any data being posted that didn't use the smallest encoding
for integers/lengths.
This is controlled by a new flag in `cmd.rs`. If this is not something
an end-user cares about they should disable it as it creates extra
fields to remember this data as well as extra code. It also necessitates
an extra dependency for `linked_hash_map`.
Resolves #11
This PR might get updated with …
> Respect deserialized format (e.g. order, en encodings)

- src/cmd.rs
- src/generation.rs
- src/intermediate.rs
- src/main.rs
- static/prelude_canonical.rs
Now that #28 allows for preserving of deserialization order, there must
be a way to force canonical serialization instead of just defaulting to
it. When PRESERVE_ENCODINGS and CANONICAL_FORM are true the
serialization traits contain a force_canonical parameter which can
override the deserialized format.
> Canonical form toggling

- src/generation.rs
- src/intermediate.rs
- src/main.rs
- src/parsing.rs
- src/test.rs
- static/serialization_preserve.rs
- tests/canonical/input.cddl
- tests/canonical/tests.rs
- tests/core/input.cddl
- tests/core/tests.rs
- tests/deser_test
- tests/preserve-encodings/input.cddl
- tests/preserve-encodings/tests.rs
- tests/rust-wasm-split/tests.rs
Supports `bytes .cbor T` which allows encoding bytes that must obey the
format of a serialized `T`. This is supported both in fields and
definitions. In the generated API any `bytes .cbor T` is treated as `T`
but in the serialization code it is treated as bytes.
Also removes the need to generate wrapper types for tagged types and
instead only uses aliases as they are essentially only a serialization
detail.
Includes a fix for the unit tests core/core_no_wasm as there was a low
chance of them failing as the tests seem to be run asynchronously which
could allow one of them to rarely have unit tests copied twice.
This replaces the PR #47 to avoid a bunch of git merging issues due to
it being based partway through #37 before it was merged and in a fork.
> .cbor spec support

- src/generation.rs
- src/intermediate.rs
- src/main.rs
- tests/preserve-encodings/tests.rs
Structs now contain all their encoding fields in encoding structs e.g.
struct `Foo` contains a `encodings: Option<FooEncoding>` which contains
all the encoding fields rather than directly in `Foo`. This should make
things a lot clearer. The encoding structs are contained within
`src/cbor_encodings.rs`.
Enums (type/group choices) were also refactored wrt encoding variables.
Enum variants with more than one field are now named structs e.g.
```
Bar{
bar: Bar,
bar_encoding_1: ...,
bar_encoding_2: ...,
}
```
to help with pattern matching so you can do `Bar{ bar, .. } =>`.
Enums with a single field remain as tuples e.g. `Bar(Bar)`.
> Move encoding fields into its own structs + enum rework

- src/generation.rs
- src/intermediate.rs
- src/utils.rs
We may want to consider f32, f64 (not sure about floating point spec in CBOR vs floating point implementation in Rust) and u128 and i128 (not sure about cbor support for these types) in the future
> Add u8, i8, u16, i16 to prelude

- Cargo.lock
- Cargo.toml
- src/comment_ast.rs
- src/intermediate.rs
- src/main.rs
- src/parsing.rs
This PR introduces a DSL embedded inside CDDL comments to help give variable names to Rust types
Example cddl:
```cddl
address = [
bytes, ; @name foo
uint ; @name bar
]
; Transactions
txout = [
address,
uint, ; @name baz
]
costmdls = {
? 0 : int ; @name plutus_v1
? 1 : int ; @name plutus_v2
}
```
Results in the following code
```rust
#[derive(Clone, Debug, serde::Deserialize, serde::Serialize, schemars::JsonSchema)]
pub struct Address {
pub foo: Vec<u8>,
pub bar: u64,
#[serde(skip)]
encodings: Option<AddressEncoding>,
}
impl Address {
pub fn new(foo: Vec<u8>, bar: u64) -> Self {
Self {
foo,
bar,
encodings: None,
}
}
}
#[derive(Clone, Debug, serde::Deserialize, serde::Serialize, schemars::JsonSchema)]
pub struct Costmdls {
pub plutus_v1: Option<Int>,
pub plutus_v2: Option<Int>, …
```
> Comment DSL to generate Rust variable names

- Cargo.lock
- Cargo.toml
- src/comment_ast.rs
- src/parsing.rs
- tests/comment-dsl/input.cddl
- tests/comment-dsl/tests.rs
This PR allows giving names to group choices. It also fixes an upstream bug in the cddl lib related to AST parsing of group choice comments
> Allow giving group choice DSL names

- src/comment_ast.rs
- src/generation.rs
- src/parsing.rs
- tests/comment-dsl/input.cddl
- tests/comment-dsl/tests.rs
> @newtype support

- src/generation.rs
- src/intermediate.rs
- src/parsing.rs
- tests/core/input.cddl
- tests/core/tests.rs
This PR fixes two issues with the prelude number detection:
1. It failed on `u64` as u64 is larger than isize (at least on my machine)
2. It failed on `int .size` notation
> Fix prelude number detection

- src/generation.rs
- src/intermediate.rs
- tests/preserve-encodings/input.cddl
When used as a key `Int` requires more traits, which can't be auto-generated when used as a tuple enum. This switches it to a named enum any ignores encoding fields for those traits. This also stops duplicate keys which were possible previously when the encoding differed.
We now only generate `Int` when it is actually referenced within the CDDL definitions being generated.
> Fix for `Int` when used as key, only gen when needed

- Cargo.lock
- Cargo.toml
- src/parsing.rs
This bumps the remote version of cddl to the ast-parent-pointer branch we need to unblock #91 
This branch also includes all the other changes, so this closes #101 and #102
> Bump to anweiss/cddl ast-parent-pointer

- src/cli.rs
- src/dep_graph.rs
- src/generation.rs
- src/intermediate.rs
- src/main.rs
- src/parsing.rs
For generating larger projects it may be desirable to generate into different files. Now --input can take a directory. If it is given a directory it will read all .cddl files and generate each in its own .rs file for export. Serialization/*Encodings are still all in one file. This resolves #95 
Also includes dependency graph ordering that fixes #93 and is essential for multi file support where the cyclic references are across file boundaries. This should also fix #98
> Multi file support + Dependency graph ordering

- src/parsing.rs
- tests/core/input.cddl
This PR fixes two different issues related to parenthesis usage:
1. Use of parenthesis in .size notations was broken (ex: `uint .size (1)`)
2. Handling of `Type2::ParenthesizedType` was missing
I still need to write tests for these two, but I'm waiting for #91
> Fix parenthesis handling on ranges and type2

- Cargo.lock
- src/generation.rs
- src/intermediate.rs
- src/parsing.rs
- tests/core/input.cddl
- tests/core/tests.rs
- tests/preserve-encodings/input.cddl
- tests/preserve-encodings/tests.rs
1) Refactor RustType (Conceptual / Serialization)
Before `RustType` represented how things are serialized e.g. `Tagged`, `CBORBytes`, etc as well as the underlying rust type we use, despite in 90% of cases us only caring about the underlying rust type. This is now split up into several structs with `RustType` being the complete type with both components and `ConceptualRustType` being the underlying rust type used outside of serialization contexts. This is work done ahead of supporting `.default` specs as that would have necessitated an additional `RustType::Default(FixedValue, Box<RustType>)` variant otherwise, further adding more serialization-only information, causing potential bugs when not properly dealt with.
2) Add `.default` support
Adds .default support to typenames (`foo = bar …
> .default support / `RustType` refactor

- src/generation.rs
- src/intermediate.rs
- static/ordered_hash_map.rs
- static/prelude.rs
- tests/canonical/tests.rs
- tests/preserve-encodings/tests.rs
Fixes for all the clippy lints/rustc warnings found when generating `babbage.cddl` in the `core` crate.
This required significant refactoring to `generate_deserialize()` to return code with extra context so we could tailor how it's used to avoid warnings/lints. The way before/after context is passed in was changed too to avoid redundant things e.g. `Ok(foo?)`.
> Clippy / warnings fixes in output code

- src/generation.rs
- src/intermediate.rs
- src/parsing.rs
- tests/core/input.cddl
- tests/core/tests.rs
e.g.:
```
foo = (uint, text)
bar = [
foos: [* foo],
]
```
which if you had `n` foos would be a `2 * n` long CBOR array as there's no wrapping map/array around the basic group `foo`. This can be done in some CDDL specs as a space optimization.
> Basic groups inside arrays support.

- src/generation.rs
- src/parsing.rs
- tests/comment-dsl/input.cddl
- tests/comment-dsl/tests.rs
I accidentally missed support for `@name` annotations for typechoices with multiple variants. This PR fixes it
At the same time, I also fixes some issue with missing newlines in the outputted code
> Add @name annotation support for typechoice variants

- Cargo.lock
- Cargo.toml
- src/generation.rs
This PR makes that all the code outputted by the codegen is sorted, closing #126 
This makes it easier to compare diffs when regenerating code
**Note:** this PR isn't based on master but the `rustfmt` branch. It needs to be merged before this one.
> Sorted outputted code

- src/generation.rs
- src/intermediate.rs
- tests/core/input.cddl
I noticed the WASM code outputted by the codegen had some issues:
If you have something like
```cddl
data = { * policy_id_v2 => { * asset_name_v2 => metadata_details } }
```
It would first generate a type for `{ * policy_id_v2 => { * asset_name_v2 => metadata_details } }` and then make `Data` an alias to that type. Instead, I made it so that Data is just directly the type instead of an alias
If in the Rust crate we had something like  `type LabelMetadataV2 = BTree<...>`, instead of reusing `core::LabelMetadataV2` in the WASM type, it would instead just redefine the alias a new alias that happens to be the same.
I now made it properly just use `core::LabelMetadataV2` so the alias gets reused
I switched `wasm_wrappers_generated.insert` to `wasm_wrappers_generated.contains`. This is because …
> Remove unnecessary WASM aliases

- src/comment_ast.rs
- src/generation.rs
- src/intermediate.rs
- src/main.rs
- src/parsing.rs
- src/test.rs
- static/prelude.rs
- static/serialization.rs
- static/serialization_non_force_canonical.rs
- static/serialization_non_preserve.rs
- static/serialization_preserve_force_canonical.rs
- tests/canonical/tests.rs
- tests/core/input.cddl
- tests/core/tests.rs
- tests/deser_test
- tests/external_core_defs
- tests/external_wasm_defs
- tests/preserve-encodings/tests.rs
- tests/rust-wasm-split/tests.rs
Aliases are not generated if you tag comments by ; @no_alias This is useful for example in babbage.cddl's `int64 = -9223372036854775808 .. 9223372036854775807 ; @no_alias` to avoid generating this.
Externally-defined types can be marked by doing:
```
address = _CDDL_CODEGEN_EXTERN_TYPE_
```
to tell cddl-codegen that this represents a type that should have its Serialize/Deserialize traits used directly (e.g. if it were a self-contained rust type) and to not worry about its definition not being present. This is very useful when you have types that are hand-written due to having a more complicated structure than could be code-generated (e.g. the spec is just `bytes` but really there is a complicated binary format here e.g. crypto stuff). This removes the need for the old hack we had to do …
> @no_alias tag + to/from bytes rework + misc fixes + external types

- src/generation.rs
- src/intermediate.rs
- src/test.rs
- static/serialization_preserve.rs
- static/serialization_preserve_force_canonical.rs
- static/serialization_preserve_non_force_canonical.rs
- tests/canonical/tests.rs
- tests/external_rust_defs_multifile
- tests/external_wasm_defs_multifile
- tests/multifile/inputs/bar.cddl
- tests/preserve-encodings/tests.rs
multi-file test updated to test json-gen output crate too
json-gen crate fixed to scope things in multiple files correctly
cbor_encodings imported per-type
removed some imports for consistency (e.g. most places used cbor_event::Special but some still used CBORSpecial. same with Sz and Type)
Includes refactoring/fixes for #137
> Multi-file json-gen schema work + less imports

- src/generation.rs
- src/intermediate.rs
- src/main.rs
- tests/core/input.cddl
- tests/core/tests.rs
- tests/preserve-encodings/input.cddl
- tests/preserve-encodings/tests.rs
Now something like:
```
redeemer_tag =
0 ; @name Spend
/ 1 ; @name Mint
/ 2 ; @name Cert
/ 3 ; @name Reward
```
Will use C-style enums e.g.:
```
pub enum RedeemerTag {
Spend,
Mint,
Cert,
Reward,
}
```
vs 129 lines generated before (with preserve-encodings). It was less without preserve-encodings, but still ended up with `RedeemerTag` and `RedeemerTagKind` being effectively the exact same type.
This also improves usability as c-style enums can be directly exposed to WASM.
For preseve-encodings targets the encoding variables are pushed up to wherever they're used, similar to how primitives (uint, text, etc) are handled.
> C-style enum support

- src/generation.rs
- src/intermediate.rs
- src/parsing.rs
- src/test.rs
- tests/comment-dsl/tests.rs
- tests/core/tests.rs
- tests/rust-wasm-split/tests.rs
When group choices contain an inlined variant with at most 1 non-fixed value into the enum variant definition.
e.g.
```
script = [ 0, native_script // 1, plutus_v1_script // 2, plutus_v2_script ]
```
would before generate 1 enum and 3 structs (of 1 element each) and it now generates only the 1 enum with the elements (`native_script`, `plutus_v1_script`, `plutus_v2_script`) being stored directly into the enum variant instead of having the wrapper intermediate structs placed there.
For non-preserve-enecodings buildings it's direct e.g.:
```
pub enum Script {
NativeScript(NativeScript),
PlutusV1Script(PlutusV1Script),
PlutusV2Script(PlutusV2Script),
}
```
and for preserve-encodings builds it's necessary to store those encoding fields somewhere so they're inlined just like we previously did …
> Embed inlined group choices into enums

- README.md
- example/supported.cddl
* Document the comment DSL
* Document CLI flags
* Mention new split rust/wasm output structure
* Remove unsupported section (to handle in issues instead as this tends to get very outdated)
> Update readme (cli flags, comment dsl, new format)

- src/parsing.rs
- tests/core/input.cddl
- tests/core/tests.rs
Fixes #164
Before this we were treating `foo = [* T]` as `foo = [T]` and creating a new 1-field struct.
Homogeneous arrays in other contexts were always working (e.g. `foo = [ bar: [* T] ]`) so were not modified.
> Fix top level general arrays

- src/generation.rs
- src/intermediate.rs
- tests/core/input.cddl
- tests/core/tests.rs
Fixes #170
Other uses of `ConceptualRustType::Rust` don't appear to cause issues. The assumption about CBOR containing 1 element still holds in both (under the assumptions required for their format).
> Optional extern/raw-bytes read_len fix

- src/generation.rs
- tests/core/input.cddl
- tests/core/tests.rs
> Always check read_len's remaining length in structs

- docs/docs/command_line_flags.mdx
- src/cli.rs
- src/generation.rs
This will help compatibility for CML and make changing any details of
these only require changing those macros instead of needing to
regenerate the library again.
This also significantly decreases the amount of repetitive boilerplate
junk making reading the files clearer.
Override for the CBOR to/from bytes API + to/from JSON
Override for the conversion traits between wasm/rust types. (e.g. From
between them + AsRef for the rust one)
> Extern macro CLI options for WASM boilerplate

- docs/docs/comment_dsl.mdx
- src/comment_ast.rs
- src/intermediate.rs
- src/parsing.rs
- tests/core/input.cddl
- tests/core/tests.rs
- tests/preserve-encodings/input.cddl
- tests/preserve-encodings/tests.rs
Allow marking a type as a key to auto-derive traits e.g. for utils code
Fixes #190
> @used_as_key dsl

- src/parsing.rs
- tests/core/input.cddl
- tests/core/tests.rs
Fixes #211
Fixes #153
Also adds in usage of `@name` into existing test cases.
> Fix @name not working on single elem group choices

- src/generation.rs
- src/intermediate.rs
- src/parsing.rs
- tests/core/input.cddl
- tests/core/tests.rs
- tests/external_wasm_defs
- tests/preserve-encodings/input.cddl
- tests/preserve-encodings/tests.rs
Check ranges and error on incorrect ones in constructors and setters in all spots.
Additional non-deserialization test checks to check the above.
Migrate few remaining usage of `JsValue` for WASM errors away to `JsError` to be consistent with the rest of the generated code.
> Full range check in rest of API

- src/generation.rs
- src/intermediate.rs
- tests/core/input.cddl
- tests/core/tests.rs
- tests/preserve-encodings/input.cddl
- tests/preserve-encodings/tests.rs
Fixes #175
Now properly checks all lengths for all variants to ensure that overlapping types parse the correct variant instead of prematurely thinking it's a subset of one.
Also fixes having CBORReadLen contributions from previous variants that tried to parse from contributing to later variant parses (possibly causing issues if it meant it already hit the limit).
Includes support for optional fields within enums that get inlined.
Tests for both cases.
> Enum length-check fixes + Enum optional field support

- static/serialization_preserve.rs
- tests/core/input.cddl
- tests/core/tests.rs
- tests/deser_test
- tests/preserve-encodings/input.cddl
- tests/preserve-encodings/tests.rs
Specifically tests for support for #121 for plain groups.
For multi arrays covered by #120
For single ones covered by #210
We are keeping #121 open for now as the case for single non-plain-groups e.g. `[uint]` is not covered. We've yet to see this used anywhere in Cardano so it's low priority to fix.
> More test cases for plain groups

- .gitignore
- docs/docs/comment_dsl.mdx
- src/comment_ast.rs
- src/generation.rs
- src/intermediate.rs
- src/parsing.rs
- src/test.rs
- static/Cargo_rust.toml
- tests/external_json_impls
- tests/json/input.cddl
- tests/json/tests.rs
Wrapper newtypes will generate custom implementations that will defer to the inner type's JSON traits instead of deriving to get them. This gives us much nicer JSON implementations allowing directly `T` instead of `{ inner: T }`.
Bytes newtypes will have a specialization that serializes to hex bytestring instead of the `[number]` array that would otherwise be used.
Introduces `@custom_json` comment DSL for newtypes that tell cddl-codegen to avoid generating/deriving any JSON traits under the assumption that some custom trait impls will be provided post-generation by the user.
> Wrapper JSON Overhaul

- src/generation.rs
- src/intermediate.rs
This is a new clippy warning that was just added and is now causing CML CI to trip up.
> Avoid clippy warning in enum deserialization  generated code

- docs/docs/comment_dsl.mdx
- src/intermediate.rs
- tests/core/input.cddl
- tests/core/tests.rs
- tests/external_rust_defs
- tests/external_rust_defs_compiles_with_json_preserve
- tests/external_wasm_defs
Allows types defined by `_CDDL_CODEGEN_EXTERN_TYPE_` to be used with generic arguments.
Generics will be used directly on the rust side, but due to wasm-bindgen restrictions must be specified for each concrete type like with current generic support.
> Extern generics

- src/cli.rs
- src/generation.rs
* Better error checks/messages for file missing related errors to help debugging as the error was incredibly opaque as to where it originated.
* Imports correctly from the common import override in `serialization.rs` files instead of relying on the `import super::*;` which only works when it's not overrided.
> Better file errors + common import import

- src/generation.rs
- src/intermediate.rs
- src/parsing.rs
- tests/core/input.cddl
- tests/core/tests.rs
- tests/preserve-encodings/input.cddl
- tests/preserve-encodings/tests.rs
Caused when the inlining would made cddl-codegen think that the types were not overlapping since it was looking at the stored type not the actual starting cbor type (e.g. when it was a fixed value).
This would cause a problem as the type matching introduced in #199 but only in very specific cases with basic groups starting with fixed values.
Various other fixes + more test cases:
Fixes #229
Fixes #230 
Fixes #231 
Fixes #232
> Fix issue with overlapping inlined basic embedded enums

- src/intermediate.rs
- src/main.rs
- src/parsing.rs
- tests/core/input.cddl
- tests/core/tests.rs
- tests/preserve-encodings/input.cddl
- tests/preserve-encodings/tests.rs
Previously this only worked on primitive wrappers.
Now you can do e.g. `foo = [* uint] ; @newtype` which was ignored before.
> @newtype on array/map wrappers

- docs/docs/comment_dsl.mdx
- src/comment_ast.rs
- src/generation.rs
- src/intermediate.rs
- src/parsing.rs
- tests/core/input.cddl
- tests/core/tests.rs
This allows us to specify doc-comments for auto-generated types to avoid users having to manually put in comments afterwards which would be overwritten every re-gen.
There is support for type-level (after the definition), field-level and variant-level (for group/type-choices).
> Add @doc comment DSL
